// react-tv/src/App.tsx
import * as React from "react";
import { apiGet } from "./api";
import { KLineHeader } from "./components/KLineHeader";
import { KLineWidget } from "./components/KLineWidget";
import Paper from "@material-ui/core/Paper";
import Grid from "@material-ui/core/Grid";
import { ws } from "./utils/socket";

function App() {
  const [name, setName] = React.useState("btcusdt");
  const [symbols, setSymbols] = React.useState<IApiSymbols[]>([]);
  React.useEffect(() => {
    ws.initWebSocket();
    apiGet<IApiSymbols[]>("public_symbols").then((res) => {
      if (!res || !res.data) {
        return;
      }
      setSymbols(res.data);
    });
  }, []);

  return (
    <div className="App">
      <Grid container spacing={1}>
        <Grid item xs>
          <Paper>
            <KLineHeader name={name} symbols={symbols} onClick={setName} />
          </Paper>
        </Grid>
        <Grid item xs={10}>
          <Paper>
            <KLineWidget symbol={name} />
          </Paper>
        </Grid>
      </Grid>
    </div>
  );
}

export default App;

// vue-tv/src/App.tsx
import { defineComponent, ref, onMounted } from "vue";
import { apiGet } from "./api";
import KLineHeader from "./components/KLineHeader";
import KLineWidget from "./components/KLineWidget";
import { ws } from "./utils/socket";

export default defineComponent({
  name: "App",
  setup() {
    const symbol = ref("btcusdt");
    const symbols = ref<Array<IApiSymbols>>([]);

    const onClick = (name: string) => {
      symbol.value = name;
      ws.evt.emit("onChangeSymbol", name);
    };

    const fetchSymbolList = () => {
      apiGet<IApiSymbols[]>("public_symbols").then((res) => {
        if (!res || !res.data) {
          return;
        }
        symbols.value = res.data;
      });
    };

    onMounted(() => {
      fetchSymbolList();
      ws.initWebSocket();
    });

    return () => (
      <div class="box">
        <div class="left-box">
          <KLineHeader
            name={symbol.value}
            symbols={symbols.value}
            onClick={onClick}
          />
        </div>
        <div class="right-box">
          <KLineWidget symbol={symbol.value} />
        </div>
      </div>
    );
  },
});
