// react-tv/src/components/KLineHeader.tsx
import * as React from "react";
import { makeStyles, Button } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
  root: {
    height: window.innerHeight,
    overflow: "scroll",
    "& > *": {
      margin: theme.spacing(1),
    },
  },
}));

type Props = {
  name: string;
  symbols: IApiSymbols[];
  onClick: (name: string) => void;
};
export const KLineHeader = (props: Props) => {
  const classes = useStyles();
  const { name, symbols, onClick } = props;

  return (
    <div className={classes.root}>
      {symbols.map((e) => {
        if (!e.tradable) {
          return null;
        }
        const isActive = name === e.name;
        return (
          <Button
            key={e.name}
            size={"small"}
            variant="outlined"
            color={isActive ? "secondary" : "primary"}
            onClick={() => onClick(e.name)}
          >
            {e.base_currency.toLocaleUpperCase()}/
            {e.quote_currency.toLocaleUpperCase()}
          </Button>
        );
      })}
    </div>
  );
};

// vue-tv/src/components/KLineHeader.tsx
import { defineComponent, PropType } from "vue";

export default defineComponent({
  name: "KLineHeader",
  props: {
    name: {
      type: String,
      required: true,
    },
    symbols: {
      type: Array as PropType<Array<IApiSymbols>>,
      required: true,
    },
    onClick: {
      type: Function as PropType<(name: string) => void>,
      required: true,
    },
  },
  setup(props) {
    return () => (
      <div class="header" style={{ height: window.innerHeight + "px" }}>
        {props.symbols.map((e) => {
          if (!e.tradable) {
            return null;
          }
          const isActive = props.name === e.name;
          return (
            <button
              key={e.name}
              class={isActive ? "secondary" : "primary"}
              onClick={() => props.onClick(e.name)}
            >
              {e.base_currency.toLocaleUpperCase()}/
              {e.quote_currency.toLocaleUpperCase()}
            </button>
          );
        })}
      </div>
    );
  },
});
