// react-tv/src/components/KLineWidget.tsx
import * as React from "react";
import { apiGet } from "../api";
// import { DataFeed, widget, GetBarsParams } from "../datafeed/datafeed";
import { DataFeed, widget, GetBarsParams } from "tradingview-api";
import {
  IChartingLibraryWidget,
  Bar,
  LibrarySymbolInfo,
} from "tradingview-api/lib/library.min";
import { ws } from "../utils/socket";

/**
 * @key Server 端定义字段
 * @value value 对应 DataFeed.configuration.supported_resolutions
 */
const intervalMap = {
  M1: "1",
  M5: "5",
  M15: "15",
  M30: "30",
  H1: "60",
  D1: "1D",
  W1: "1W",
  MN: "1M",
};

type Props = {
  symbol: string;
};

type IntervalT = keyof typeof intervalMap;
export class KLineWidget extends React.Component<Props> {
  private symbol = this.props.symbol;
  private interval: IntervalT = "M5";
  private _widget?: IChartingLibraryWidget;
  private datafeed = new DataFeed({
    getBars: (params) => this.getBars(params),
    fetchResolveSymbol: () => this.resolveSymbol(),
  });

  public resolveSymbol = () => {
    return new Promise<LibrarySymbolInfo>((resolve) => {
      const symbol = this.symbol;
      resolve({
        name: symbol.toLocaleUpperCase(),
        full_name: symbol.toLocaleUpperCase(),
        description: symbol.toLocaleUpperCase(),
        type: symbol,
        session: "24x7",
        exchange: "BTB",
        listed_exchange: symbol,
        timezone: "Asia/Shanghai",
        format: "price",
        pricescale: Math.pow(10, 2),
        minmov: 1,
        volume_precision: 10,
        has_intraday: true,
        supported_resolutions: ["1", "5", "15", "30", "60", "D", "1W", "1M"],
      });
    });
  };

  public getBars = async (params: GetBarsParams) => {
    const symbol = this.symbol;
    if (params.resolution !== intervalMap[this.interval]) {
      this.unsubscribeKLine();
      for (let key in intervalMap) {
        if (intervalMap[key as IntervalT] === params.resolution) {
          this.interval = key as IntervalT;
        }
      }
    }
    const res = await apiGet<Array<IApiCandles>>(
      "market_candles",
      `/${this.interval}/${symbol}`,
      {
        params: {
          before: params.to,
          limit: window.innerWidth || 1000,
        },
      }
    );
    if (
      params.resolution === intervalMap[this.interval] &&
      params.firstDataRequest &&
      res &&
      res.data.length
    ) {
      this.subscribeKLine();
    }

    if (!res || !res.data || !res.data.length) {
      return {
        bars: [],
        meta: { noData: true },
      };
    }
    const list: Bar[] = [];
    for (let i = 0; i < res.data.length; i++) {
      const item = res.data[i];
      list.push({
        time: item.id * 1000,
        open: item.open,
        high: item.high,
        low: item.low,
        close: item.close,
        volume: item.base_vol,
      });
    }
    list.sort((l, r) => (l.time > r.time ? 1 : -1));
    return {
      bars: list,
      meta: {
        noData: !list.length,
      },
    };
  };

  public subscribeKLine = () => {
    const symbol = this.symbol;
    ws.subscribe(
      `candle.${this.interval}.${symbol}`,
      {
        cmd: "sub",
        args: [`candle.${this.interval}.${symbol}`],
        id: "react-tv",
      },
      (data: IApiCandles) => {
        this.datafeed.updateKLine({
          time: data.id * 1000,
          open: data.open,
          high: data.high,
          low: data.low,
          close: data.close,
          volume: data.base_vol,
        });
      }
    );
  };

  public unsubscribeKLine = () => {
    const symbol = this.symbol;
    ws.unsubscribe(`candle.${this.interval}.${symbol}`);
  };

  public initTradingView = () => {
    const symbol = this.symbol;
    this._widget = new widget({
      // debug: true,
      fullscreen: true,
      symbol: symbol.toLocaleUpperCase(),
      interval: intervalMap[this.interval],
      container_id: "tv_chart_container",
      datafeed: this.datafeed,
      library_path: "/charting_library/",
      locale: "zh",
      theme: "Dark",
      timezone: "Asia/Shanghai",
    });
  };

  public setSymbol = (symbol: string) => {
    this.unsubscribeKLine();
    this.symbol = symbol;
    this._widget?.setSymbol(symbol, intervalMap[this.interval], () => {
      console.log("------setSymbol---------");
    });
  };

  public componentDidMount() {
    this.initTradingView();
  }

  public componentWillUnmount() {
    this._widget && this._widget.remove();
  }

  public render() {
    return (
      <div className="kline">
        <div id="tv_chart_container"></div>
      </div>
    );
  }
}

// vue3-typescript-demo/src/components/KLineWidget.vue
<script setup lang="ts">
import { DataFeed, widget as TvWidget } from "tradingview-api";
import type { GetBarsParams } from "tradingview-api";
import type {
  IChartingLibraryWidget,
  LibrarySymbolInfo,
} from "tradingview-api/lib/library.min";
import { onMounted, ref, toRefs, watch } from "vue";
import { getKlineHistory } from "@/api";
import { intervalMap, supported_resolutions } from "@/utils/hardCode";
import { ws } from "@/utils/socket";

const props = defineProps({
  symbol: {
    type: String,
    default: "",
  },
  symbolInfo: {
    type: Object,
    required: true,
  },
});

const widget = ref<IChartingLibraryWidget | null>(null);
const interval = ref("5min");
const { symbol, symbolInfo } = toRefs(props);

/** 訂閱websocket */
const subscribeKLine = () => {
  ws.subscribe(
    `market.${symbol.value.toLocaleLowerCase()}.kline.${interval.value}`,
    {
      id: "react-tv",
      sub: `market.${symbol.value.toLocaleLowerCase()}.kline.${interval.value}`,
    },
    (data) => {
      const tick = data.tick;
      datafeed.value.updateKLine({
        time: tick.id * 1000,
        open: tick.open,
        high: tick.high,
        low: tick.low,
        close: tick.close,
        volume: tick.vol,
      });
    }
  );
};

/** websocket取消訂閱 */
const unsubscribeKLine = () => {
  ws.unsubscribe(`market.${symbol.value}.kline.${interval.value}`);
};
/** 取得數據 訂閱數據 */
const getBars = async (params: GetBarsParams) => {
  try {
    console.log("params: ", params);
    const size = window.innerWidth;
    // 是否第一次請求歷史數據
    if (!params.firstDataRequest) {
      return {
        bars: [],
        meta: {
          noData: true,
        },
      };
    }
    if (params.resolution !== intervalMap[interval.value]) {
      unsubscribeKLine();
      for (const key in intervalMap) {
        if (intervalMap[key] === params.resolution) {
          interval.value = key;
        }
      }
    }
    const symbolFlag = symbol.value.split(" ").join("");
    // do api get history
    const [list] = await getKlineHistory({
      symbol: symbolFlag.toLocaleLowerCase(),
      period: interval.value,
      size: size > 2000 ? 2000 : size,
    });

    console.log("list: ", list);

    if (
      params.resolution === intervalMap[interval.value] &&
      params.firstDataRequest &&
      list
    ) {
      subscribeKLine();
    }

    if (!list) {
      return {
        bars: [],
        meta: { noData: true },
      };
    }
    return {
      bars: list,
      meta: {
        noData: !list.length,
      },
    };
  } catch (error) {
    console.log("getBars error:", error);
    throw error;
  }
};
/** 配置trading-view */
const resolveSymbol = (): Promise<LibrarySymbolInfo> => {
  return new Promise((resolve) => {
    resolve({
      name: symbol.value,
      full_name: symbol.value,
      description: symbol.value,
      type: symbol.value,
      session: "24x7",
      exchange: "HuoBi",
      listed_exchange: symbol.value,
      timezone: "Asia/Shanghai",
      format: "price",
      pricescale: Math.pow(10, symbolInfo.value["price-precision"]),
      minmov: 1,
      volume_precision: symbolInfo.value["value-precision"],
      has_intraday: true,
      supported_resolutions: supported_resolutions,
    });
  });
};

const datafeed = ref(
  new DataFeed({
    getBars: (params: GetBarsParams) => getBars(params),
    fetchResolveSymbol: () => resolveSymbol(),
    fetchConfiguration: () => {
      return new Promise((resolve) => {
        resolve({
          supported_resolutions,
        });
      });
    },
  })
);

/** 初始化trading-view */
const initTradingView = () => {
  widget.value = new TvWidget({
    fullscreen: true,
    symbol: symbol.value,
    interval: intervalMap[interval.value],
    container_id: "tv_chart_container",
    datafeed: datafeed.value,
    library_path: "/charting_library/",
    locale: "zh",
    theme: "Dark",
    timezone: "Asia/Shanghai",
  });
};

const setSymbol = (newSymbol: string) => {
  unsubscribeKLine();
  symbol.value = newSymbol;
  widget.value?.setSymbol(
    newSymbol.toLocaleUpperCase(),
    intervalMap[interval.value],
    () => {
      console.log("------setSymbol---------", symbol.value);
    }
  );
};
watch(symbol, (newsymbol) => {
  setSymbol(newsymbol);
});

onMounted(() => {
  initTradingView();
});
</script>

<template>
  <div class="kline">
    <div id="tv_chart_container" />
  </div>
</template>
