// react-typescript-demo/src/components/KLineHeader.tsx
import * as React from "react";
import { makeStyles, Button } from "@material-ui/core";

const useStyles = makeStyles((theme) => ({
  root: {
    height: window.innerHeight,
    overflow: "scroll",
    "& > *": {
      margin: theme.spacing(1),
    },
  },
}));

type Props = {
  name: string;
  symbols: IApiSymbols[];
  onClick: (name: string) => void;
};
export const KLineHeader = (props: Props) => {
  const classes = useStyles();
  const { name, symbols, onClick } = props;

  return (
    <div className={classes.root}>
      {symbols.map((e) => {
        if (e.state !== "online") {
          return null;
        }
        const isActive = name === e.symbol;
        return (
          <Button
            key={e.symbol}
            size={"small"}
            variant="outlined"
            color={isActive ? "secondary" : "primary"}
            onClick={() => onClick(e.symbol)}
          >
            {e["base-currency"].toLocaleUpperCase()}/
            {e["quote-currency"].toLocaleUpperCase()}
          </Button>
        );
      })}
    </div>
  );
};

// vue-javascript-demo/src/components/KLineHeader.vue
<template>
  <div class="header" :style="{ height: height + 'px' }">
    <button
      v-for="item in symbolList"
      :key="item.symbol"
      :class="item.symbol === symbol ? 'secondary' : 'primary'"
      @click="$emit('onClick', item)"
    >
      {{ item["base-currency"].toLocaleUpperCase() }}/{{
        item["quote-currency"].toLocaleUpperCase()
      }}
    </button>
  </div>
</template>

<script>
export default {
  name: "KLineHeader",
  props: {
    symbol: String,
    symbolList: Array,
  },
  data() {
    return {
      height: window.innerHeight,
    };
  },
};
</script>
